// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Usado pelo Prisma Migrate (CLI). Em runtime, o PrismaClient usa o
    // driver adapter configurado em lib/db.ts.
    url: process.env["DATABASE_URL"],
  },
});
