// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Usado pelo Prisma Migrate (CLI). Em runtime, o PrismaClient usa o
    // driver adapter configurado em lib/db.ts.
    // Migrations precisam da conexao DIRETA (sem pooler): o PgBouncer da Neon
    // nao suporta os advisory locks / DDL em transacao que o Migrate usa.
    // Em producao defina DIRECT_URL com a string "unpooled" da Neon.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
